language: node_js

node_js:
  - 'v4'

services:
  - mysql

addons:
  apt:
    packages:
    - graphicsmagick
env:
  NODE_ENV: 'test'

before_script:
  - mysql -e 'create database test;'

notifications:
  email:
    - alberto@wejs.org

after_success:
- npm install coveralls
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
