language: node_js

node_js:
  - 'v4'

services:
  - mysql

addons:
  apt:
    packages:
    - graphicsmagick
env:
  NODE_ENV: 'test'

before_script:
  - mysql -e 'create database test;'

notifications:
  email:
    - alberto@wejs.org

after_success:
  - NODE_ENV=test LOG_LV=info node_modules/.bin/istanbul cover node_modules/.bin/_mocha -- -u exports -R spec test/bootstrap.js test/**/*.test.js --timeout 20000
